from fastapi import APIRouter
from app.schemas.models import AgentLaunchRequest
from app.agent.strategy_agent import StrategyAgent
from app.db.sqlite import create_campaign_from_strategy

router = APIRouter(prefix="/agent", tags=["agent"])

strategy_agent = StrategyAgent()


@router.post("/launch")
async def launch_agent(payload: AgentLaunchRequest):
    offering = payload.offering
    icp = payload.icp

    positioning = await strategy_agent.generate_positioning(offering, icp)
    messaging = await strategy_agent.generate_messaging(offering, icp, positioning)
    sequence_plan = await strategy_agent.generate_sequence(offering, icp, positioning, messaging)

    strategy_json = strategy_agent.compose_campaign_strategy(
        offering=offering,
        icp=icp,
        positioning=positioning,
        messaging=messaging,
        sequence_plan=sequence_plan
    )

    sequence_json = strategy_agent.to_runner_sequence_json(sequence_plan)
    run_config_json = strategy_agent.default_run_config()

    campaign_id = create_campaign_from_strategy(
        name=sequence_plan.get("sequence_name", "Autogenerated Campaign"),
        strategy_json=strategy_json,
        sequence_json=sequence_json,
        run_config_json=run_config_json
    )

    # Runner kick: for now, simply set status=running; your runner polling will pick it up
    return {
        "campaign_id": campaign_id,
        "status": "running",
        "summary": {
            "target_market": positioning.get("target_customer"),
            "value_prop": positioning.get("value_prop"),
            "themes": [t.get("name") for t in messaging.get("themes", [])][:3],
            "steps": [s.get("step_id") for s in sequence_plan.get("steps", [])],
        }
    }
